### ISSUE TITLE
Add a setting for changing notification time

### ISSUE THREAD

**Issue by jmreicha** [Pramod-sj/Daily-Word#6]
I love everything about the app other than the fact I get notified very early in the morning. I would love to have an option to specify what time the daily word notification is delivered.

**Comment by Pramod-sj** [comment]
Hello jmreicha,
Due to busy schedule I'm unable to invest enough time on this, will surely look in this.

**Comment by Pramod-sj** [comment]
Hey jmreicha,
This has been implemented and is included in the latest release (v3.0.0) on the Play Store as a Beta feature. Excited to see how it goes and looking forward to your feedback!

**Comment by jmreicha** [comment]
Woo. I’ll give it a try!
